#!/bin/bash
PATH=/bin:/usr/bin:/sbin:/usr/sbin

START_IPSEC_ENABLED=`cat /etc/ipcsystools.conf | grep ^ipsec.start_enabled | cut -d"=" -f2`
if [ $START_IPSEC_ENABLED -eq 1 ]; then
	/usr/sbin/ipsec restart &
fi
