#!/bin/bash

# Basis Bibliothek für die IPCs
. /usr/share/ipcsystools/ipclib.inc

if check_ifupdown_on_mobile_connection ; then 
	syslogger "debug" "interface $IFACE : 3G led off"
	/usr/bin/ipc-set-led 3g off
else
	syslogger "debug" "interface $IFACE : no action"
fi

exit 0

