#!/bin/bash
# This script will be called on connection shutdown
# Uses  /etc/network/if-?.d and /etc/ppp/ip-?.d directories.
#  See manual pages for differences in env variables!

. /usr/share/ipcsystools/ipclib.inc

if check_ifupdown_on_mobile_connection ; then 
	led=`get_on_mobile_connection_led`
	if [ -n "$led" ] ; then
		/usr/bin/ipc-set-led $led off
		syslogger "debug" "interface $IFACE : $led LED off"
	fi
else
	syslogger "debug" "interface $IFACE : no if-down action"
fi

exit 0

