#!/bin/bash
# This script will be called on connection shutdown
# Uses  /etc/network/if-?.d and /etc/ppp/ip-?.d directories.
#  See manual pages for differences in env variables!

. /usr/share/ipcsystools/ipclib.inc

if check_ifupdown_on_mobile_connection ; then 
	if [ '$PPP_TTYNAME' = 'usbmodem-data' ] ; then
		syslogger "debug" "interface $IFACE : 3G led off"
		/usr/bin/ipc-set-led 3g off
	else
		syslogger "debug" "interface $IFACE : Option1 led off"
		/usr/bin/ipc-set-led option1 off
	fi
else
	syslogger "debug" "interface $IFACE : no action"
fi

exit 0

