#!/bin/bash

# Basis Bibliothek für die IPCs
. /usr/share/ipcsystools/ipclib.inc

#set -x

wan_ifs="`getipcoption general.wan.interfaces`"
hit=false
for wan_if in $wan_ifs; do
	if [ "$IFACE" = "`getipcoption connection.$wan_if.dev`" ]; then
		hit=true; break
	fi
done

if [ $hit = true ] ; then 
	syslogger "debug" "interface $IFACE : ipsec stop"
	START_IPSEC_ENABLED=`cat /etc/ipcsystools.conf | grep ^ipsec.start_enabled | cut -d"=" -f2`
	if [ $START_IPSEC_ENABLED -eq 1 ]; then
		/usr/sbin/ipsec stop &
	fi
fi

exit 0
