#!/bin/bash

# Basis Bibliothek für die IPCs
. /usr/share/ipcsystools/ipclib.inc

#set -x

wan_ifs="`getipcoption general.wan.interfaces`"
hit=false
for wan_if in $wan_ifs; do
	if [ "$IFACE" = "`getipcoption connection.$wan_if.dev`" ]; then
		hit=true; break
	fi
done

if [ $hit = true ] ; then 
	syslogger "debug" "interface $IFACE : ovpn stop"
	START_OVPN_ENABLED=`cat /etc/ipcsystools.conf | grep ^ovpn.start_enabled | cut -d"=" -f2`
	if [ $START_OVPN_ENABLED -eq 1 ] ; then
		invoke-rc.d openvpn stop client &
	fi
fi

exit 0
