#!/bin/bash

# Basis Bibliothek für die IPCs
. /usr/share/ipcsystools/ipclib.inc

if check_ifupdown_on_mobile_connection ; then 
	syslogger "debug" "interface $IFACE : ovpn stop"
	START_OVPN_ENABLED=`cat /etc/ipcsystools.conf | grep ^ovpn.start_enabled | cut -d"=" -f2`
	if [ $START_OVPN_ENABLED -eq 1 ] ; then
		invoke-rc.d openvpn stop client &
	fi
fi

exit 0
