#!/bin/bash
#set -x
value=0
if [ -e /var/run/ipcsystools/gps_status ]; then
	value=(`cat /var/run/ipcsystools/gps_status | sed -n -e 's/^Current time: \(.*\)$/\1/ p' | tr ':' ' '`)
	gpstime=${value[0]}${value[1]}${value[2]}${value[4]}${value[5]}.${value[6]}
	date --date=$gpstime +%s
else
	echo 0
fi

