#!/bin/bash
#set -x
rc=0
if [ -e /var/run/ipcsystools/connection_mode ]; then
	value=`cat /var/run/ipcsystools/connection_mode`
	case $value in
	LTE*)  rc=4;;
	HS*)   rc=3;;
	UMTS*) rc=2;;
	GPRS*) rc=1;;
	esac
fi;
echo $rc

