#!/bin/bash
### BEGIN INIT INFO
# Provides:          
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4
# Default-Stop:			 
# Short-Description: Startup the IPC Enviroment
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
. /usr/share/ipcsystools/ipclib.inc

DESC="ipc-startup[$$]"

syslogger "info" "Startup IPC environment... "

/usr/sbin/ipc-startup
