#!/bin/bash
### BEGIN INIT INFO
# Provides:          
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4
# Default-Stop:			 
# Short-Description: Startup the IPC Enviroment
### END INIT INFO

/usr/bin/ipc-set-led all-off

# Basis Bibliothek f?r die MCB-2
. /usr/share/ipcsystools/ipclib.inc

echo "Startup IPC environment... "

# Start a new subshell for modem stuff
(
	# Initialize the UMTS Modem
	InitializeModem

	# Startup WAN Connection
	startup_wan_connection
)

# Set "ready" Led on
/usr/bin/ipc-set-led ready on

exit 0
