#!/bin/bash
### BEGIN INIT INFO
# Provides:          
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     0 6
# Default-Stop:			 
# Short-Description: Shutdown the IPC Enviroment
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
. /usr/share/ipcsystools/ipclib.inc

DESC="ipc-shutdown[$$]"

syslogger "info" "Shuting down ipc environment... "

/usr/sbin/ipc-shutdown

# WWAN LED off
echo 0 > /sys/class/gpio/gpio174/value 2> /dev/null

syslogger "info" "Shutdown mcb environment complete"
exit 0
