#!/bin/bash
# This script will be called on connection pre-startup
#  /etc/network/if-?.d only - Called for DIP and ETH interfaces, 
# PPP(OE) interfaces use /etc/ppp/ip-?.d and will not process this
# script!!!

. /usr/share/ipcsystools/ipclib.inc

if check_ifupdown_on_mobile_connection ; then 
	# Only DIP and ETH connections will enter here. See above.
	led=get_on_mobile_connection_led
	if [ -n "$led" ] ; then
		/usr/bin/ipc-set-led $led timer
		syslogger "debug" "interface $IFACE : $led LED blinking"
	fi

else
	syslogger "debug" "interface $IFACE : no pre-up action"
fi

exit 0


