#!/bin/bash
# This script will be called on connection startup
# Uses  /etc/network/if-?.d and /etc/ppp/ip-?.d directories.
#  See manual pages for differences in env variables!

. /usr/share/ipcsystools/ipclib.inc

if check_ifupdown_on_mobile_connection ; then 
	syslogger "debug" "interface $IFACE : ipsec restart"
	START_IPSEC_ENABLED=`cat /etc/ipcsystools.conf | grep ^ipsec.start_enabled | cut -d"=" -f2`
	if [ $START_IPSEC_ENABLED -eq 1 ]; then
		/usr/sbin/ipsec restart &
	fi
fi

exit 0
