#!/bin/bash
# This script will be called on connection startup
# Uses  /etc/network/if-?.d and /etc/ppp/ip-?.d directories.
#  See manual pages for differences in env variables!

. /usr/share/ipcsystools/ipclib.inc

if check_ifupdown_on_mobile_connection ; then 
	syslogger "debug" "interface $IFACE : ovpn restart"
	START_OVPN_ENABLED=`cat /etc/ipcsystools.conf | grep ^ovpn.start_enabled | cut -d"=" -f2`
	if [ $START_OVPN_ENABLED -eq 1 ] ; then
#FIXME		invoke-rc.d openvpn start client &
		/etc/init.d/openvpn start client &
	fi
fi

exit 0
