#!/bin/bash
# Shutdown ipcsystools and terminate umts connection
echo -n "Shutdown ipc environment... "

# Terminate possibly running PPP daemon
PPP_PIDS=`pidof pppd`
kill -TERM $PPP_PIDS 2> /dev/null

# Software Hardreset for modem
. /usr/share/ipcsystools/ipclib.inc
DetectModemCard
if [ $? -eq 0 ]; then
	umtscardtool -s 'at!greset' 
fi

if which ipc-set-led > /dev/null; then
	ipc-set-led all-off
fi

echo "done."
exit 0
