#!/bin/bash
# Shutdown ipcsystools and terminate mobile connection
echo -n "Shutdown ipc environment... "

rm -f /var/run/ipcsystools.enabled

# Terminate possibly running PPP daemon
PPP_PIDS=`pidof pppd`
kill -TERM $PPP_PIDS 2> /dev/null


# Software Hardreset for modem
. /usr/share/ipcsystools/ipclib.inc
DetectModemCard
if [ $? -eq 0 ]; then
	ipc-set-led ready on
	shutdown_wan_connection
	ipc-set-led 3g off
	# Check for config trigger and call backends, or do nothing
	config_wan_connections
	if [ $? -ne 0 ]; then
		umtscardtool -s 'at!greset' > /dev/null && sleep 1
	fi
fi

if which ipc-set-led > /dev/null; then
	ipc-set-led all-off
fi

echo "done."
exit 0
