#!/bin/bash
# Initialize ipcsystools for operation
#  - detecting the umts modem
#  - starting the initial connection
echo -n "Startup IPC environment... "

if which ipc-set-led; then
	/usr/bin/ipc-set-led all-off
fi

# Initialize modem (apn, sim, ...)
. /usr/share/ipcsystools/ipclib.inc
InitializeModem

# Startup WAN connection	
if [ ! -e /etc/ipcsystools.disable ] ; then
	startup_wan_connection
else
	echo -n "(ipcsystools disabled) "
fi

if which ipc-set-led; then
	ipc-set-led ready on
fi

echo "done."
exit 0
