.\"
.TH ipc-umts-fs 1 "Feb. 2012" "Ubuntu"
.SH NAME
ipc-umts-ni \- get the network information from umts modem
.SH SYNOPSIS
.B ipc-umts-ni
.SH DESCRIPTION
.B ipc-umts-ni
return the network information from the connected GPRS/UMTS modem and outputs
the value to stdout.
.I The script will poll the modem until some answer is received.
.SH AUTHOR
Carsten Schlote

