#!/bin/bash
#-----------------------------------------------------------------------
PATH=/bin:/usr/bin:/sbin:/usr/sbin
. /usr/share/ipcsystools/ipclib.inc

DESC="ipc-service[$$]"

IPC_SERVICE_PID_FILE=$IPC_STATUSFILE_DIR/ipc-service.pid
IPC_SERVICE_STATUS=$IPC_STATUSFILE_DIR/ipc-service-status

IPC_SERVICE_ENABLED=`getipcoption general.service_enabled 1`
IPC_SERVICE_INTERVAL=`getipcoption reportstatus.interval`

running=true

#-- Start of script ----------------------------------------------------

if [ "$IPC_SERVICE_ENABLED" = "1" ]; then
	obtainlock $IPC_SERVICE_PID_FILE
	syslogger "debug" "Started ipc service"

	cd $IPC_SCRIPTS_DIR

	if [ ! -e $IPC_SERVICE_STATUS ]; then
		syslogger "debug" "First run of script, init service status"
		echo -n "0" > $IPC_SERVICE_STATUS
	fi

	while $running; do
		let tdiff=`date +%s`-`cat $IPC_SERVICE_STATUS`
		let tdiff=$tdiff-$IPC_SERVICE_INTERVAL

		if [ $tdiff -ge 0 ]; then
			syslogger "debug" "Executing ipc service loop"
			date +%s > $IPC_SERVICE_STATUS

			$IPC_SCRIPTS_DIR/ipc-cronjobs.sh
		else
			syslogger "debug" "Reporting next ipc status in $tdiff seconds"
			sleep $tdiff
		fi
	done

	syslogger "debug" "Finished ipc service"
	releaselock
else
    syslogger "debug" "ipc-service disabled"
fi

#-- End of script ------------------------------------------------------

