#!/bin/bash
# Initialize ipcsystools for operation
#  - detecting the UMTS/LTE modem
#  - starting the initial connection
echo -n "Startup IPC environment... "

if which ipc-set-led  > /dev/null ; then
	/usr/bin/ipc-set-led all-off
fi

if [ -e /etc/ptxdist_version ] ; then
	echo -n "(init MCB2) "
	/usr/share/ipcsystools/ipc-initsystem.sh install
fi

function start_services
{
	# Startup WAN connection	
	if [ ! -e /etc/ipcsystools.disable ] ; then
		echo -n "(cron enabled) "
		(startup_wan_connection &)
		touch /var/run/ipcsystools.enabled
	else
		echo -n "(cron disabled) "
		rm -f /var/run/ipcsystools.enabled
	fi
}

# Create path to status files
if ! [ -e $IPC_STATUSFILE_DIR ]; then
	mkdir -p $IPC_STATUSFILE_DIR
fi

# Initialize modem (apn, sim, ...)
. /usr/share/ipcsystools/ipclib.inc
InitializeModem
DetectModemCard
if [ $? -eq 0 ]; then
	start_services
fi

if which ipc-set-led > /dev/null ; then
	ipc-set-led ready on
fi

echo "done."
exit 0
