#!/bin/sh

function log ()
{
	logger -p local0.notice -t ip-up $@
	mkdir -p /usr/share/kp-web/logfiles/
	echo `date` "  ;ip-down; " $@ >> /usr/share/kp-web/logfiles/connection.log
}

log "time: $CONNECT_TIME  | rcvd: $BYTES_RCVD | sent: $BYTES_SENT"

