#!/bin/sh

function log ()
{
	logger -p local0.notice -t ip-up $@
	mkdir -p /usr/share/kp-web/logfiles/
	echo `date` "  ;ip-up; " $@ >> /usr/share/kp-web/logfiles/connection.log
}

log "Current-IP: $PPP_IFACE $PPP_LOCAL"

