#!/bin/sh
#
# Start or stop the ipcsystools service
#

### BEGIN INIT INFO
# Provides:          ipcsystools
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:		 0 1 6
# Short-Description: IPC Systools Service
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
IPC_DOWN=/usr/sbin/ipc-shutdown
IPC_UP=/usr/sbin/ipc-startup

[ ! -f /etc/default/rcS ] || . /etc/default/rcS
test -f /lib/lsb/init-functions || exit 1
. /lib/lsb/init-functions

if [ "$VERBOSE" = "no" ]; then
	echo "Huhuhuhuu" $1 $2
fi

case "${1}" in
("start")
    log_begin_msg "Starting IPC Systools services..."
    ${IPC_UP}
    log_end_msg $?
    exit $?
    ;;
("stop")
    log_begin_msg "Stopping IPC Systools services..."
	# WWAN LED off (FIXME)
	echo 0 > /sys/class/gpio/gpio174/value 2> /dev/null
    ${IPC_DOWN}
    log_end_msg $?
    exit $?
    ;;
("restart" | "force-reload")
    "${0}" stop
    "${0}" start
    ;;
(*)
    log_success_msg "Usage: /etc/init.d/apmd {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac
