#!/bin/bash
PATH=/bin:/usr/bin:/sbin:/usr/sbin

START_OVPN_ENABLED=`cat /etc/mcbctl.conf | grep ^ovpn.start_enabled | cut -d"=" -f2`
if [ $START_VPN_ENABLED -eq 1]; then
	/etc/init.d/openvpn start &
fi
