.\"
.TH ipc-umts-fs 1 "Feb. 2012" "Ubuntu"
.SH NAME
ipc-startup \- Initializes the ipcsystools for operation
.SH SYNOPSIS
.B ipc-startup
.SH DESCRIPTION
.B ipc-startup
will check and setup available modems. It also prepares any other information
required by the cron scripts.
.SH AUTHOR
Carsten Schlote

